### ISSUE TITLE
Time ranges not working

### ISSUE THREAD

**Issue by wrender** [coffeemonster/RT-Extension-TimeWorkedReport#1]
Great extension for RT. We are using RT 4.2.7 with the latest version of the Time Worked Report.   We are having an issue with it.   At the end of the month yesterday we entered in time on a ticket, and when we run reports for dates that include that date and time period the time does not show up. If we set the end date to be a couple of days later it shows up.  It seems like a bug?

For example the time was entered onto a ticket for 2014/09/30  11:45pm.

When we run a Time Worked Report for the start date of:  2014-09-01 00:00:00   and end date of: 2014-10-01 00:00:00   The time does not show up that was entered at 11:45pm on the 30th.

In our RT_SiteConfig file we have the timezone set to: Set( $Timezone, 'America/Edmonton');  UTC -7 hours.

**Comment by coffeemonster** [comment]
Hi wrender,
Thanks for your feedback - always good to hear from a user :)
I won't have time to look at this before the weekend - hope you can wait for a fix.
Cheers,
/Alister

**Comment by wrender** [comment]
Hi Alister,

Thanks for getting back to me.  No problem and I am happy to help out (I’m just not a very strong programmer). Talk to you soon.

Wesley Render, Consultant

Phone: 1.403.228.1221 ext 201

 http://www.otherdata.com/ www.otherdata.com

 http://www.facebook.com/otherdata

**Comment by wrender** [comment]
hi coffeemonster.  It appears that extension does not account for our correct timezone. I am still doing some further testing.

**Comment by coffeemonster** [comment]
Closing - v1.05 merged in localtimezone change which fixes this issue.
