### ISSUE TITLE
Ability to break out time by day, not by ticket

### ISSUE THREAD

**Issue by wrender** [coffeemonster/RT-Extension-TimeWorkedReport#4]
After talking to accounting/hr/payroll people, one major problem we have found with this extension is that it does not break out a person's time by day.  It would be nice if this extension could do this.  I looked over the code, but couldn't figure out how to best adjust it to break everything out by day. Unfortunately it is just a bit over my head as I am only a basic programmer.

Also, it would be nice if there was some sort of widget where a person with appropriate permissions could adjust the "Created" date/time for TimeWorked entries in the Transactions table in RT.

Wes

**Comment by coffeemonster** [comment]
Hi Wes,

Thanks for the feedback.
Can you provide an example of how you want the output to look?
It shouldn't be too hard to change, but i'm not sure how to group into tickets/dates when you have multiple times on different dates on the same ticket.

e.g would this be suitable?
user | date | ticket | hours
frank | 2014-10-10 | 313 | 5hr
frank | 2014-10-10 | 314 | 1hr
frank | 2014-10-12 | 313 | 1hr

Let me know your thoughts on this. I should be able to get something done about this over the holiday period.

Cheers,
/Alister

**Comment by coffeemonster** [comment]
I have updated the plugin to default to breaking down by user/date/ticket (instead of just user/ticket).
Let me know how you get on with this and i'll create a CPAN release.

**Comment by wrender** [comment]
Hi Coffeemonster.  Sorry for the late reply. Thanks for adjusting this.  That looks really good!

Maybe one thing I would suggest is being able to put in the ticket subject.  That way an accounting department/management would also have a basic description of what was worked on.

Unfortunately we ended up switching back to using the support system built into our web hosting platform, WHMCS so will not be using RT anymore.  I'm sure this stuff could benefit a lot of companies that are using RT though.

Cheers
