### ISSUE TITLE
What is the unit ?

### ISSUE THREAD

**Issue by alexisthethe** [coffeemonster/RT-Extension-TimeWorkedReport#6]
What is the unit of Time spent values in RT ? I cannot find this information. Is it minutes or days ?
@coffeemonster  @wrender

**Comment by coffeemonster** [comment]
@alexisthethe - I believe TimeTaken is stored as minutes. It is displayed as mins and hours.
Eg `73m | 1.2h`

https://github.com/coffeemonster/RT-Extension-TimeWorkedReport/blob/master/html/Tools/Reports/TimeWorkedReport.html#L305
